// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://llcheplsmuqjzdvjksot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsY2hlcGxzbXVxanpkdmprc290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzg1ODUsImV4cCI6MjA3MDk1NDU4NX0.9lsmie_oZ309m71FWYJWBEO_KVBeIhkoR3_99qhrdC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);